USE MyDB;

CREATE TABLE Students(
	Id TINYINT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	FullName NVARCHAR(50) NOT NULL,
	PlusPointsCount TINYINT NOT NULL,
	MinusPointCount TINYINT NOT NULL,
	StudentWeight TINYINT NULL,
	CreatedAT DATETIME2 DEFAULT GETDATE()
)